#!/usr/bin/env node
'use strict';

/*
 * This script generates the template a changelog by comparing a current version
 * with the latest commit in a branch. Run this, copy what's logged into the
 * `CHANGELOG.md` and update the top section based on the changes listed in
 * "Community Contributions"
 *
 * Usage:
 *
 * dev/changelog <branch-name (Default: master)>
 */

const generate = require('./src/generate');

let currentVersion = `v${require('package').version}`;
let branch = process.argv[2] || 'master';

generate(currentVersion, branch)
  .then(changelog => console.log(changelog))
  .catch(error => console.error(error));
